// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nfn.proto

package nfn

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscribeContext struct {
	NodeName             string   `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeContext) Reset()         { *m = SubscribeContext{} }
func (m *SubscribeContext) String() string { return proto.CompactTextString(m) }
func (*SubscribeContext) ProtoMessage()    {}
func (*SubscribeContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b809db4a7814953, []int{0}
}

func (m *SubscribeContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeContext.Unmarshal(m, b)
}
func (m *SubscribeContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeContext.Marshal(b, m, deterministic)
}
func (m *SubscribeContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeContext.Merge(m, src)
}
func (m *SubscribeContext) XXX_Size() int {
	return xxx_messageInfo_SubscribeContext.Size(m)
}
func (m *SubscribeContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeContext.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeContext proto.InternalMessageInfo

func (m *SubscribeContext) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

type Notification struct {
	CniType string `protobuf:"bytes,1,opt,name=cni_type,json=cniType,proto3" json:"cni_type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Notification_InSync
	//	*Notification_ProviderNwCreate
	//	*Notification_ProviderNwRemove
	Payload              isNotification_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b809db4a7814953, []int{1}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetCniType() string {
	if m != nil {
		return m.CniType
	}
	return ""
}

type isNotification_Payload interface {
	isNotification_Payload()
}

type Notification_InSync struct {
	InSync *InSync `protobuf:"bytes,2,opt,name=in_sync,json=inSync,proto3,oneof"`
}

type Notification_ProviderNwCreate struct {
	ProviderNwCreate *ProviderNetworkCreate `protobuf:"bytes,3,opt,name=provider_nw_create,json=providerNwCreate,proto3,oneof"`
}

type Notification_ProviderNwRemove struct {
	ProviderNwRemove *ProviderNetworkRemove `protobuf:"bytes,4,opt,name=provider_nw_remove,json=providerNwRemove,proto3,oneof"`
}

func (*Notification_InSync) isNotification_Payload() {}

func (*Notification_ProviderNwCreate) isNotification_Payload() {}

func (*Notification_ProviderNwRemove) isNotification_Payload() {}

func (m *Notification) GetPayload() isNotification_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Notification) GetInSync() *InSync {
	if x, ok := m.GetPayload().(*Notification_InSync); ok {
		return x.InSync
	}
	return nil
}

func (m *Notification) GetProviderNwCreate() *ProviderNetworkCreate {
	if x, ok := m.GetPayload().(*Notification_ProviderNwCreate); ok {
		return x.ProviderNwCreate
	}
	return nil
}

func (m *Notification) GetProviderNwRemove() *ProviderNetworkRemove {
	if x, ok := m.GetPayload().(*Notification_ProviderNwRemove); ok {
		return x.ProviderNwRemove
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Notification) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Notification_InSync)(nil),
		(*Notification_ProviderNwCreate)(nil),
		(*Notification_ProviderNwRemove)(nil),
	}
}

type ProviderNetworkCreate struct {
	ProviderNwName       string      `protobuf:"bytes,1,opt,name=provider_nw_name,json=providerNwName,proto3" json:"provider_nw_name,omitempty"`
	Vlan                 *VlanInfo   `protobuf:"bytes,2,opt,name=vlan,proto3" json:"vlan,omitempty"`
	Direct               *DirectInfo `protobuf:"bytes,3,opt,name=direct,proto3" json:"direct,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProviderNetworkCreate) Reset()         { *m = ProviderNetworkCreate{} }
func (m *ProviderNetworkCreate) String() string { return proto.CompactTextString(m) }
func (*ProviderNetworkCreate) ProtoMessage()    {}
func (*ProviderNetworkCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b809db4a7814953, []int{2}
}

func (m *ProviderNetworkCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderNetworkCreate.Unmarshal(m, b)
}
func (m *ProviderNetworkCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderNetworkCreate.Marshal(b, m, deterministic)
}
func (m *ProviderNetworkCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderNetworkCreate.Merge(m, src)
}
func (m *ProviderNetworkCreate) XXX_Size() int {
	return xxx_messageInfo_ProviderNetworkCreate.Size(m)
}
func (m *ProviderNetworkCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderNetworkCreate.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderNetworkCreate proto.InternalMessageInfo

func (m *ProviderNetworkCreate) GetProviderNwName() string {
	if m != nil {
		return m.ProviderNwName
	}
	return ""
}

func (m *ProviderNetworkCreate) GetVlan() *VlanInfo {
	if m != nil {
		return m.Vlan
	}
	return nil
}

func (m *ProviderNetworkCreate) GetDirect() *DirectInfo {
	if m != nil {
		return m.Direct
	}
	return nil
}

type ProviderNetworkRemove struct {
	ProviderNwName       string   `protobuf:"bytes,1,opt,name=provider_nw_name,json=providerNwName,proto3" json:"provider_nw_name,omitempty"`
	VlanLogicalIntf      string   `protobuf:"bytes,2,opt,name=vlan_logical_intf,json=vlanLogicalIntf,proto3" json:"vlan_logical_intf,omitempty"`
	DirectProviderIntf   string   `protobuf:"bytes,3,opt,name=direct_provider_intf,json=directProviderIntf,proto3" json:"direct_provider_intf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderNetworkRemove) Reset()         { *m = ProviderNetworkRemove{} }
func (m *ProviderNetworkRemove) String() string { return proto.CompactTextString(m) }
func (*ProviderNetworkRemove) ProtoMessage()    {}
func (*ProviderNetworkRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b809db4a7814953, []int{3}
}

func (m *ProviderNetworkRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderNetworkRemove.Unmarshal(m, b)
}
func (m *ProviderNetworkRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderNetworkRemove.Marshal(b, m, deterministic)
}
func (m *ProviderNetworkRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderNetworkRemove.Merge(m, src)
}
func (m *ProviderNetworkRemove) XXX_Size() int {
	return xxx_messageInfo_ProviderNetworkRemove.Size(m)
}
func (m *ProviderNetworkRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderNetworkRemove.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderNetworkRemove proto.InternalMessageInfo

func (m *ProviderNetworkRemove) GetProviderNwName() string {
	if m != nil {
		return m.ProviderNwName
	}
	return ""
}

func (m *ProviderNetworkRemove) GetVlanLogicalIntf() string {
	if m != nil {
		return m.VlanLogicalIntf
	}
	return ""
}

func (m *ProviderNetworkRemove) GetDirectProviderIntf() string {
	if m != nil {
		return m.DirectProviderIntf
	}
	return ""
}

type VlanInfo struct {
	VlanId               string   `protobuf:"bytes,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	ProviderIntf         string   `protobuf:"bytes,2,opt,name=provider_intf,json=providerIntf,proto3" json:"provider_intf,omitempty"`
	LogicalIntf          string   `protobuf:"bytes,3,opt,name=logical_intf,json=logicalIntf,proto3" json:"logical_intf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VlanInfo) Reset()         { *m = VlanInfo{} }
func (m *VlanInfo) String() string { return proto.CompactTextString(m) }
func (*VlanInfo) ProtoMessage()    {}
func (*VlanInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b809db4a7814953, []int{4}
}

func (m *VlanInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VlanInfo.Unmarshal(m, b)
}
func (m *VlanInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VlanInfo.Marshal(b, m, deterministic)
}
func (m *VlanInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VlanInfo.Merge(m, src)
}
func (m *VlanInfo) XXX_Size() int {
	return xxx_messageInfo_VlanInfo.Size(m)
}
func (m *VlanInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VlanInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VlanInfo proto.InternalMessageInfo

func (m *VlanInfo) GetVlanId() string {
	if m != nil {
		return m.VlanId
	}
	return ""
}

func (m *VlanInfo) GetProviderIntf() string {
	if m != nil {
		return m.ProviderIntf
	}
	return ""
}

func (m *VlanInfo) GetLogicalIntf() string {
	if m != nil {
		return m.LogicalIntf
	}
	return ""
}

type DirectInfo struct {
	ProviderIntf         string   `protobuf:"bytes,1,opt,name=provider_intf,json=providerIntf,proto3" json:"provider_intf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectInfo) Reset()         { *m = DirectInfo{} }
func (m *DirectInfo) String() string { return proto.CompactTextString(m) }
func (*DirectInfo) ProtoMessage()    {}
func (*DirectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b809db4a7814953, []int{5}
}

func (m *DirectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectInfo.Unmarshal(m, b)
}
func (m *DirectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectInfo.Marshal(b, m, deterministic)
}
func (m *DirectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectInfo.Merge(m, src)
}
func (m *DirectInfo) XXX_Size() int {
	return xxx_messageInfo_DirectInfo.Size(m)
}
func (m *DirectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DirectInfo proto.InternalMessageInfo

func (m *DirectInfo) GetProviderIntf() string {
	if m != nil {
		return m.ProviderIntf
	}
	return ""
}

type InSync struct {
	NodeIntfIpAddress    string   `protobuf:"bytes,1,opt,name=node_intf_ip_address,json=nodeIntfIpAddress,proto3" json:"node_intf_ip_address,omitempty"`
	NodeIntfMacAddress   string   `protobuf:"bytes,2,opt,name=node_intf_mac_address,json=nodeIntfMacAddress,proto3" json:"node_intf_mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InSync) Reset()         { *m = InSync{} }
func (m *InSync) String() string { return proto.CompactTextString(m) }
func (*InSync) ProtoMessage()    {}
func (*InSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b809db4a7814953, []int{6}
}

func (m *InSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InSync.Unmarshal(m, b)
}
func (m *InSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InSync.Marshal(b, m, deterministic)
}
func (m *InSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InSync.Merge(m, src)
}
func (m *InSync) XXX_Size() int {
	return xxx_messageInfo_InSync.Size(m)
}
func (m *InSync) XXX_DiscardUnknown() {
	xxx_messageInfo_InSync.DiscardUnknown(m)
}

var xxx_messageInfo_InSync proto.InternalMessageInfo

func (m *InSync) GetNodeIntfIpAddress() string {
	if m != nil {
		return m.NodeIntfIpAddress
	}
	return ""
}

func (m *InSync) GetNodeIntfMacAddress() string {
	if m != nil {
		return m.NodeIntfMacAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*SubscribeContext)(nil), "SubscribeContext")
	proto.RegisterType((*Notification)(nil), "Notification")
	proto.RegisterType((*ProviderNetworkCreate)(nil), "ProviderNetworkCreate")
	proto.RegisterType((*ProviderNetworkRemove)(nil), "ProviderNetworkRemove")
	proto.RegisterType((*VlanInfo)(nil), "VlanInfo")
	proto.RegisterType((*DirectInfo)(nil), "DirectInfo")
	proto.RegisterType((*InSync)(nil), "InSync")
}

func init() {
	proto.RegisterFile("nfn.proto", fileDescriptor_5b809db4a7814953)
}

var fileDescriptor_5b809db4a7814953 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x5e, 0xd8, 0xd4, 0x34, 0xa7, 0x1d, 0xb4, 0x47, 0x1b, 0x14, 0x10, 0xd2, 0xc8, 0x6e, 0x2a,
	0x2e, 0xd2, 0x6d, 0xdc, 0x72, 0x03, 0x43, 0x68, 0x91, 0xa0, 0x42, 0x19, 0xe2, 0xd6, 0x72, 0x1d,
	0x07, 0x59, 0x4b, 0x8f, 0xa3, 0xd4, 0xb4, 0xe4, 0x01, 0x78, 0x0e, 0x5e, 0x8f, 0xc7, 0x40, 0xb1,
	0x93, 0xfe, 0xac, 0xbb, 0xe1, 0x2e, 0x39, 0xdf, 0xf9, 0x7e, 0x6c, 0xf9, 0x83, 0x80, 0x32, 0x8a,
	0x8a, 0x52, 0x1b, 0x1d, 0x4e, 0x60, 0x70, 0xfb, 0x73, 0xb6, 0x10, 0xa5, 0x9a, 0xc9, 0x6b, 0x4d,
	0x46, 0xfe, 0x32, 0xf8, 0x12, 0x02, 0xd2, 0xa9, 0x64, 0xc4, 0xe7, 0x72, 0xe4, 0x9d, 0x79, 0xe3,
	0x20, 0xe9, 0xd6, 0x83, 0x29, 0x9f, 0xcb, 0xf0, 0xaf, 0x07, 0xfd, 0xa9, 0x36, 0x2a, 0x53, 0x82,
	0x1b, 0xa5, 0x09, 0x9f, 0x43, 0x57, 0x90, 0x62, 0xa6, 0x2a, 0xda, 0x65, 0x5f, 0x90, 0xfa, 0x56,
	0x15, 0x12, 0x43, 0xf0, 0x15, 0xb1, 0x45, 0x45, 0x62, 0xf4, 0xe8, 0xcc, 0x1b, 0xf7, 0xae, 0xfc,
	0x28, 0xa6, 0xdb, 0x8a, 0xc4, 0xcd, 0x41, 0xd2, 0x51, 0xf6, 0x0b, 0x3f, 0x01, 0x16, 0xa5, 0x5e,
	0xaa, 0x54, 0x96, 0x8c, 0x56, 0x4c, 0x94, 0x92, 0x1b, 0x39, 0x3a, 0xb4, 0xeb, 0x4f, 0xa3, 0xaf,
	0x0d, 0x34, 0x95, 0x66, 0xa5, 0xcb, 0xbb, 0x6b, 0x8b, 0xde, 0x1c, 0x24, 0x83, 0x96, 0x33, 0x5d,
	0xb9, 0xd9, 0x7d, 0x9d, 0x52, 0xce, 0xf5, 0x52, 0x8e, 0x8e, 0x1e, 0xd6, 0x49, 0x2c, 0xba, 0xab,
	0xe3, 0x66, 0x1f, 0x02, 0xf0, 0x0b, 0x5e, 0xe5, 0x9a, 0xa7, 0xe1, 0x6f, 0x0f, 0x4e, 0x1f, 0x0c,
	0x80, 0x63, 0x18, 0x6c, 0x9b, 0x6d, 0x5d, 0xd4, 0xe3, 0x8d, 0x60, 0x7d, 0x5d, 0xf8, 0x0a, 0x8e,
	0x96, 0x39, 0xa7, 0xe6, 0xfc, 0x41, 0xf4, 0x3d, 0xe7, 0x14, 0x53, 0xa6, 0x13, 0x3b, 0xc6, 0x73,
	0xe8, 0xa4, 0xaa, 0x94, 0xc2, 0x34, 0x27, 0xee, 0x45, 0x1f, 0xed, 0xaf, 0x5d, 0x69, 0xa0, 0xf0,
	0xcf, 0x7e, 0x0e, 0x17, 0xf6, 0x3f, 0x72, 0xbc, 0x81, 0x61, 0x6d, 0xc8, 0x72, 0xfd, 0x43, 0x09,
	0x9e, 0x33, 0x45, 0x26, 0xb3, 0xa1, 0x82, 0xe4, 0x49, 0x0d, 0x7c, 0x76, 0xf3, 0x98, 0x4c, 0x86,
	0x17, 0x70, 0xe2, 0x9c, 0xd9, 0x5a, 0xdc, 0xae, 0x1f, 0xda, 0x75, 0x74, 0x58, 0x1b, 0xa8, 0x66,
	0x84, 0x77, 0xd0, 0x6d, 0x0f, 0x86, 0xcf, 0xc0, 0xb7, 0x4e, 0x2a, 0x6d, 0xa2, 0x74, 0xea, 0xdf,
	0x38, 0xc5, 0x73, 0x38, 0xde, 0xd5, 0x73, 0xf6, 0xfd, 0x62, 0x4b, 0x09, 0x5f, 0x43, 0x7f, 0x27,
	0xa2, 0xf3, 0xec, 0xe5, 0x9b, 0x78, 0xe1, 0x25, 0xc0, 0xe6, 0x92, 0xf6, 0x55, 0xbd, 0x7d, 0xd5,
	0x30, 0x87, 0x8e, 0x7b, 0x78, 0x38, 0x81, 0x13, 0xfb, 0xb6, 0xeb, 0x55, 0xa6, 0x0a, 0xc6, 0xd3,
	0xb4, 0x94, 0x8b, 0x45, 0xc3, 0x1a, 0xd6, 0x58, 0xcd, 0x88, 0x8b, 0xf7, 0x0e, 0xc0, 0x4b, 0x38,
	0xdd, 0x10, 0xe6, 0x5c, 0xac, 0x19, 0x2e, 0x3d, 0xb6, 0x8c, 0x2f, 0x5c, 0x34, 0x94, 0xab, 0x77,
	0xb6, 0x60, 0xb6, 0x24, 0x15, 0x4e, 0x20, 0x58, 0x17, 0x0c, 0x87, 0xd1, 0xfd, 0xb2, 0xbd, 0x38,
	0x8e, 0xb6, 0xdb, 0x74, 0xe1, 0xcd, 0x3a, 0xb6, 0x98, 0x6f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xad, 0x54, 0x7e, 0xa2, 0xa5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NfnNotifyClient is the client API for NfnNotify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NfnNotifyClient interface {
	Subscribe(ctx context.Context, in *SubscribeContext, opts ...grpc.CallOption) (NfnNotify_SubscribeClient, error)
}

type nfnNotifyClient struct {
	cc grpc.ClientConnInterface
}

func NewNfnNotifyClient(cc grpc.ClientConnInterface) NfnNotifyClient {
	return &nfnNotifyClient{cc}
}

func (c *nfnNotifyClient) Subscribe(ctx context.Context, in *SubscribeContext, opts ...grpc.CallOption) (NfnNotify_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NfnNotify_serviceDesc.Streams[0], "/nfnNotify/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &nfnNotifySubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NfnNotify_SubscribeClient interface {
	Recv() (*Notification, error)
	grpc.ClientStream
}

type nfnNotifySubscribeClient struct {
	grpc.ClientStream
}

func (x *nfnNotifySubscribeClient) Recv() (*Notification, error) {
	m := new(Notification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NfnNotifyServer is the server API for NfnNotify service.
type NfnNotifyServer interface {
	Subscribe(*SubscribeContext, NfnNotify_SubscribeServer) error
}

// UnimplementedNfnNotifyServer can be embedded to have forward compatible implementations.
type UnimplementedNfnNotifyServer struct {
}

func (*UnimplementedNfnNotifyServer) Subscribe(req *SubscribeContext, srv NfnNotify_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterNfnNotifyServer(s *grpc.Server, srv NfnNotifyServer) {
	s.RegisterService(&_NfnNotify_serviceDesc, srv)
}

func _NfnNotify_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeContext)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NfnNotifyServer).Subscribe(m, &nfnNotifySubscribeServer{stream})
}

type NfnNotify_SubscribeServer interface {
	Send(*Notification) error
	grpc.ServerStream
}

type nfnNotifySubscribeServer struct {
	grpc.ServerStream
}

func (x *nfnNotifySubscribeServer) Send(m *Notification) error {
	return x.ServerStream.SendMsg(m)
}

var _NfnNotify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nfnNotify",
	HandlerType: (*NfnNotifyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _NfnNotify_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nfn.proto",
}
